"""Add achievements field to Profile model

Revision ID: 071461fe799f
Revises: 
Create Date: 2026-05-08 20:57:50.884061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071461fe799f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievements', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('achievements')

    # ### end Alembic commands ###
